name: Build PDF

on:
  push:
    branches: [master]

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"
    - uses: actions/checkout@v2
    - name: Build and Make
      run: docker-compose up
    - name: rename output file
      run: mkdir complete && cp output/quiz.pdf complete/quiz_${{ steps.date.outputs.date }}.pdf
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: PDF
        path: complete/quiz_${{ steps.date.outputs.date }}.pdf
